name: Forward Logs

on: [push]

jobs:
  forward_logs:
    runs-on: ubuntu-latest
    env:
      AXIOM_TOKEN: xaat-09506dff-88e7-4b27-b21e-6344482ccb81
      AXIOM_ORG_ID: imlunahey-9dym
      AXIOM_DATASET: github-actions-forwarding
    steps:
      # Setup logs
      - name: Setup syslog
        run: sudo apt-get install rsyslog -y
      - name: Install axiom syslog proxy
        run: cd /tmp && wget https://github.com/axiomhq/axiom-syslog-proxy/releases/download/v0.5.0/axiom-syslog-proxy_0.5.0_linux_amd64.tar.gz && tar xvzf ./axiom-syslog-proxy_*.tar.gz
      - name: Start axiom syslog proxy
        run: /tmp/axiom-syslog-proxy_0.5.0_linux_amd64/axiom-syslog-proxy &

      # Setup bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Test
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: bun run test
