name: Forward Logs

on: [push]

jobs:
  forward_logs:
    runs-on: ubuntu-latest
    steps:
      # Setup bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Test
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install deps
        run: bun install
      - name: Test
        run: bun run test

      # Logs
      - name: Download workflow logs
        run: |
          mkdir logs
          curl -s -o logs/logs.txt -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/logs"

      - name: Create structured logs
        env:
          API_TOKEN: xaat-09506dff-88e7-4b27-b21e-6344482ccb81
          DATASET_NAME: github-actions-forwarding
        run: |
          # Parse and structure the logs as JSON objects
          while IFS= read -r line; do
            timestamp=$(echo "$line" | awk '{print $1}')
            content=$(echo "$line" | cut -d ' ' -f 3-)
            
            # Check if the log line contains a [command] tag
            if [[ "$content" =~ \[command\].* ]]; then
                type="command"
                command=$(echo "$content" | sed -E 's/\[command\]//')
                
                # Extract command arguments as an array
                IFS=' ' read -ra args <<< "$command"
                
                content=""
            else
                type=$(echo "$line" | awk '{print $2}')
                command=""
                args=()
            fi
            
            json="{\"timestamp\":\"$timestamp\",\"type\":\"$type\",\"command\":\"$command\",\"args\":$(printf '%s\n' "${args[@]}" | jq -R . | jq -s -c .),\"content\":\"$content\"}"
            echo "$json" >> structured_logs.json
            done < logs/logs.txt

      - name: Send logs to Axiom
        env:
          API_TOKEN: xaat-09506dff-88e7-4b27-b21e-6344482ccb81
          DATASET_NAME: github-actions-forwarding
        run: |
          cat structured_logs.json | curl -X 'POST' 'https://api.axiom.co/v1/datasets/'$DATASET_NAME'/ingest' \
          -H 'Authorization: Bearer '$API_TOKEN \
          -H 'Content-Type: application/x-ndjson' \
          -d @-
