name: Forward Logs

on: [push]

permissions:
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Setup bun
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Test
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install deps
        run: bun install
      - name: Test
        run: bun run test
  forward_logs:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download workflow logs
        run: |
          mkdir logs
          LAST_JOB_ID=$(curl -s -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" \
                        "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runs/${{ github.run_id }}/jobs" | jq -r '.jobs[-2].id')
          echo "LAST_JOB_ID: $LAST_JOB_ID"

          LOG_URL="https://api.github.com/repos/${{ github.repository }}/actions/jobs/$LAST_JOB_ID/logs"
          echo "LOG_URL: $LOG_URL"

          curl -L -s -o /tmp/logs.txt -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $LOG_URL
          LOG_SIZE=$(stat -c '%s' /tmp/logs.txt)
          echo "LOG_SIZE: $LOG_SIZE"

      - name: Structure logs
        run: |
          # Initialize an empty array to store the objects
          objects=()

          # Initialize variables to store the current object data
          timestamp=""
          data=""

          # Read the log line by line
          while IFS= read -r line; do
              # Check for timestamp lines
              if [[ $line =~ ^([0-9T:.]+Z) ]]; then
                # If data exists, add the current object to the array
                if [ -n "$data" ]; then
                  objects+=("{\"timestamp\":\"$timestamp\",\"logs\":$data}")
                fi
                # Reset the data variable and store the new timestamp
                data=""
                timestamp="${BASH_REMATCH[1]}"
              else
                # Append the line to the data variable
                data+="$(echo "$line" | jq -Rs .),"
              fi
          done < <(cat /tmp/logs.txt)

          # Add the last object to the array
          if [ -n "$data" ]; then
            objects+=("{\"timestamp\":\"$timestamp\",\"data\":$data}")
          fi

          # Specify the output file name
          output_file="/tmp/parsed_log_output.json"

          # Save the structured logs
          echo $objects | jq > $output_file

          echo "Parsed log data has been saved to $output_file"

      - name: Send logs to Axiom
        env:
          API_TOKEN: xaat-09506dff-88e7-4b27-b21e-6344482ccb81
          DATASET_NAME: github-actions-forwarding
        run: |
          cat /tmp/parsed_log_output.json | curl -X 'POST' 'https://api.axiom.co/v1/datasets/'$DATASET_NAME'/ingest' \
            -H 'Authorization: Bearer '$API_TOKEN \
            -H 'Content-Type: application/x-ndjson' \
            -d @-
